# === AWS Database Connection ===
# These variables ${...} will be injected by the AWS EC2 environment
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# === Prod Logging (Quiet) ===
# Disable SQL logging in prod to save disk space and performance
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.type.descriptor.sql=info

# === JPA ===
# In Prod, we strictly validate. We NEVER let Hibernate auto-update schemas.
spring.jpa.hibernate.ddl-auto=validate