name: Frontend CI (Build Only)

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install Dependencies
      run: npm install

    - name: Test Build
      run: npm run build           # Verifies the code can compile